---
- name: install.redhat | install required system packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3
    - python3-devel
    - python3-pip
    - python3-dnf
